name: pull request

on:
  push:
    branches:
      - develop

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge
          branch: develop
          reviewers: kyohmizu
